services:
  - type: web
    name: biblioteca-digital-ocr
    env: python

    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr tesseract-ocr-por poppler-utils
      pip install -r requirements.txt

    startCommand: gunicorn app:app